#GOAL: To deploy the built and tested image to an EC2 instance
name: CD
on:
  workflow_call: # allows this workflow to be called from another workflow
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      
      
      - name: Run Docker container using docker compose
        run: docker compose up -d --build --force-recreate