#Goal is to call the workflows in the order to implement shift left
name: DevSecOps
on:
  push:

jobs:
  #Secret Scanning
   secret-scanning:
       uses: ./.github/workflows/secrets-scanning.yml 
       secrets: inherit
#Code Lint and Test
   code-lint-and-test:
       needs: secret-scanning
       uses: ./.github/workflows/lint_and_test.yml
#SAST Scan
   sast-scan:
       needs: code-lint-and-test
       uses: ./.github/workflows/sonar_scan.yml
       secrets: inherit
#Dependency Scanning
   dependency-scan:
       needs: sast-scan
       uses: ./.github/workflows/dependecy_scan.yml
  #Code Build and Scan
   build-and-scan:
        secrets: inherit
        needs: dependency-scan
        uses: ./.github/workflows/trivy_scans.yml
  #Code Deploy
  #deploy:
       #secrets: inherit        
       #needs: [code-lint-and-test, build-and-push]
       #uses: ./.github/workflows/cd.yml