#Goal: To scan the code tokens, secrets, API keys or any leaked Passwords so that 
#if found, we can quickly rotate the exposed secrets and prevent any security breach.

#name of the workflow 
name: secrets scanning
#Resuable workflow that can be called from other workflows
on:
 workflow_call: # allows this workflow to be called from another workflow

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # from very first commit pull to the all code (Fetch all history for all branches and tags)
      - name: Scan for Leaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:         
          config: .github/.gitleaks.toml 
          continue-on-error: true