#Goal: To scan the statc code for SAST and code related issues using sonarqube scanner
name: Sonar Scan

on:
  workflow_call: # allows this workflow to be called from another workflow
permissions:
  contents: read
  security-events: write

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # from very first commit pull to the all code (Fetch all history for all branches and tags)
      - name: CodeQL Scan
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${matrix.language}"

      - name: SonarQube Server Scan
        uses: sonarsource/sonarqube-scan-action@v8.2.1
        with:
          args: >
            -Dsonar.projectKey=e-commerce-tws-github-actions
            -Dsonar.organization=ayush007kumar
            -Dsonar.projectName=e-commerce-tws-github-actions
            -Dsonar.branch.name=main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #sonar.io url