#Goal: To scan the statc code for SAST and code related issues using sonarqube scanner
name: Sonar Scan
on:
  workflow_call: # allows this workflow to be called from another workflow  
jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: SonarQube Server Scan
        uses: sonarsource/sonarqube-scan-action@v8.2.1
        with:
          args: >
            -Dsonar.projectKey=e-commerce-tws-github-actions
            -Dsonar.organization=ayush007kumar
            -Dsonar.projectName=e-commerce-tws-github-actions
            -Dsonar.branch.name=main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #sonar.io url